### PR TITLE
Upgrade gradle.

### PR DESCRIPTION
**Pull request by portlek**

### CODE REVIEW

**Comment by ipsk** [comment]
This requires prior testing, I remember upgrading Gradle when 7.0 first came out and it had tons of errors due to Shadow.

**Comment by portlek** [comment]
@ipsk it's passing all test. do you know how to test this PR locally?

**Comment by portlek** [comment]
idk bu it's working well :D
image

**Comment by portlek** [comment]
Probably it's about amount of repository but it's downloading the files really slow.

**Comment by Vshnv** [comment]
This might be mostly due to dynamic resolution. We are currently working on a initial compile time resolution for 1.2.5 which shoul d make this process a lot faster.

**Comment by ipsk** [comment]
Alright, I tested this a bit more and it seems fine to merge.

**Review by ipsk — APPROVED** [review]
Alright, I tested this a bit more and it seems fine to merge.

**Pull request merged**
